name: Deploy
on:
  workflow_run:
    workflows:
      - Test
    branch:
      - master
      - production
    types:
      - completed

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'v13.x' }}
    steps:
      - run: echo "ey-core deploy -e techvalidate_staging_v6 --ref ${{ github.event.workflow_run.head_branch }}"
  deploy-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'production' }}
    steps:
      - run: echo "ey-core deploy -e techvalidate_production_v6 --ref ${{ github.event.workflow_run.head_branch }}"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
